### ISSUE TITLE
Cant loot for long

### ISSUE THREAD

**Issue by Felipefpl** [Argent77/A7-TotLM-BG2EE#10]
I have the latest version of the mod plus BGEE 2.6.6.0 and i cant keep the loot's screen open for long after clicking in the chest, the screen goes back to what it was before like if i had clicked to leave the loot's screen. Savegame attached.

Edit - for some reason this seems to happen with the thief, i dont remember if this happened with the fighters/mage.

[000000028-Cant loot for long.zip](https://github.com/Argent77/A7-TotLM-BG2EE/files/12504600/000000028-Cant.loot.for.long.zip)

**Comment by Argent77** [comment]
From what I can see it looks like your character script interferes with opening chests. Your script is set to continuously scan for traps. Opening a chest disables the "find traps" action which is immediately turned on by the script again. This closes the loot screen. You can either turn off Party AI or select another script to prevent this behavior. It has nothing to do with the mod itself.

**Comment by Felipefpl** [comment]
I understand, thanks for the info, it's a pity this isnt explained in the script. It's surely a flaw from the devs.
