### ISSUE TITLE
Main game's interference

### ISSUE THREAD

**Issue by Felipefpl** [Argent77/A7-TotLM-BG2EE#11]
If you rest in this place or even other places inside the castle assassins from the main game/story will come after me to kill me, this makes no sense in the story of Luremaster:
[000000028-Assassins from main game come after me.zip](https://github.com/Argent77/A7-TotLM-BG2EE/files/12504638/000000028-Assassins.from.main.game.come.after.me.zip)

Small observation: outside you see a small section of the map with a small "square" from all sides, it's been YEARS since i played Luremaster so i dont remember if this area looked like this. ;)

**Comment by Argent77** [comment]
I can't reproduce it on vanilla SoD with TotLM installed using the attached save. Resting repeatedly didn't spawn any hostile encounters for me.

There are several areas where rest encounters will be spawned, but these small tower maps are none of them.

You could run a changelog on the area file to see if some other mods made some changes:
```
weidu --change-log id9708.are
```

Could you provide a screenshot of the second issue?

**Comment by Felipefpl** [comment]
Strange, i got a cutscene involving the man in hood and after that there were assassins after me inside the tower.

About the 2nd issue:
![Sem título](https://github.com/Argent77/A7-TotLM-BG2EE/assets/5569804/635ce945-6673-4f91-82cf-186f4d01711b)

**Comment by Argent77** [comment]
> Strange, i got a cutscene involving the man in hood and after that there were assassins after me inside the tower.

Oh, I didn't know you were talking about the dream cutscene taking place at rest. I skipped it to get a clean rest. Yes, I can reproduce the spawning of assassins. However, that shouldn't happen if you start the quest regularly. These attackers appear to be from the assassination cutscene in the Ducal Palace where Imoen is attacked, right at the start of the game.

Did you start the quest regularly by talking to Hobart after arriving at the Coalition Camp or Dragonspear Castle?

> About the 2nd issue:

I don't see anything unusual about the map. The maps of the eastern and western battlements are rather small. If you zoom out you can quickly see the edges of the maps. You might (mis)remember the map from the original game which is played in a smaller resolution.

**Comment by Argent77** [comment]
> Oh, I didn't know you were talking about the dream cutscene taking place at rest. I skipped it to get a clean rest. Yes, I can reproduce the spawning of assassins. However, that shouldn't happen if you start the quest regularly. These attackers appear to be from the assassination cutscene in the Ducal Palace where Imoen is attacked, right at the start of the game.

I looked it up more thoroughly. The SoD game scripting can be easily screwed up if you fast-forward the plot by skipping crucial events. The dream cutscene takes place on several maps, including the map from the Ducal Palace. However, that same map is scripted to spawn the assassination event, so you will encounter assassins after the rest. That happens only if you skipped the Ducal Palace event, since the dream cutscene is supposed to be triggered after all these events took place. It has nothing to do with the mod.

**Comment by Felipefpl** [comment]
I understand, thanks for the infos. :+1:
