### ISSUE TITLE
Characters arent displayed properly

### ISSUE THREAD

**Issue by Felipefpl** [Argent77/A7-TotLM-BG2EE#13]
Although the file is saved as utf-8 the characters arent displayed as they should, i got the latest build:
![Sem título](https://github.com/Argent77/A7-TotLM-BG2EE/assets/5569804/9235a602-8cf8-4cf9-ab14-d499e57b3c80)

**Comment by Argent77** [comment]
Proper unicode support for the console is only available since Windows 8 or Windows 10.

You could probably manually set the default codepage to utf-8, but that is not advisable since many command line tools may not work correctly with utf-8.

**Comment by Argent77** [comment]
Closing since this issue is a technical restriction of outdated Windows versions.
