### ISSUE TITLE
Suggestion: Better early hints

### ISSUE THREAD

**Issue by rubyFeedback** [Argent77/A7-TotLM-BG2EE#7]
I am playing it right now and I got into some places, but now I am stuck since I don't know where to go.

Could it be made more explicit which way to go? I got a book that speaks about some six items, but I am not sure which ones these are and what to do. I have to do online research now to find out what to do next.

I am not necessarily asking to dumb down the mod, but to provide better clues via dialogue/text where to go, what to do and what not. I am probably missing something obvious ...

**Comment by rubyFeedback** [comment]
After this walkthrough it became more clear:

https://gamefaqs.gamespot.com/pc/430803-icewind-dale-heart-of-winter/faqs/10898

I think all you need to do is to make the messages a bit better.

For instance, perhaps some old sign that shows the tower; and when pulling a lever
indicating "a noise to to the southeast" or something like that. So not really big changes,
just more info. I was totally confused after the riddle and the map design was also
alien to me on a first arrival.

**Comment by rubyFeedback** [comment]
I noticed the bottom right staircase was auto-repaired after pulling a lever
AND walking on it. This was a bit confusing.

Perhaps a tooltip icon could be shown "this staircase seems badly damaged"
and perhaps the wood nearby could be used to repair it. No clue why a lever
helps with the broken staircase - that seems odd. What happens exactly
when the lever is pulled?

**Comment by Argent77** [comment]
> For instance, perhaps some old sign that shows the tower; and when pulling a lever indicating "a noise to to the southeast" or something like that.

I don't think additional hints to find the towers are needed. The courtyard is rather small, and there are only very few places of interest you can visit. I agree that feedback when pulling the levers could be improved though.

> I noticed the bottom right staircase was auto-repaired after pulling a lever AND walking on it. This was a bit confusing.

The staircase isn't damaged. There's an illusionary gap in the staircase that is automatically dispelled when you approach it. It hasn't to do with any levers or switches.

**Comment by Argent77** [comment]
Solved in [v4.0](https://github.com/Argent77/A7-TotLM-BG2EE/releases/tag/v4.0).
