### ISSUE TITLE
File name conflict HOW vs BGEE

### ISSUE THREAD

**Issue by RoxanneSHS** [Argent77/A7-TotLM-BG2EE#8]
The file Netrig1.BCS  from HoW also exists with different content in BGEE (Neera's quest in the cave Rila's body to bury).
It is overwritten by the mod if installed in EET.

**Comment by Argent77** [comment]
Thanks. Will be fixed.

**Comment by Argent77** [comment]
Fixed in f2516552e8ef3ef35d1b739a5ea59559641e2559
